version: '1'
services:
  app:
    image: web
    build:
      context: .
      dockerfile: .docker/build/Dockerfile
    environment:
      - DEBUG=1
    volumes:
      - .:/var/www/html
    command: php artisan app:assessment-report
  test:
    image: test
    build:
      context: .
      dockerfile: .docker/build/Dockerfile.test
    environment:
      - DEBUG=1
    volumes:
      - .:/var/www/html
    command: php artisan test